{
  "before_script": "set +e; unset -f cd; CFLAGS=\"$CFLAGS -O2 -Wall -Wextra -Wformat -Wformat-security\"; export CFLAGS; set -ex && rm -rf build* && mkdir build-mksh build-lksh && cp GNUmakefile build-mksh && cp GNUmakefile build-lksh && (cd build-mksh && sh ../Build.sh -M) && (cd build-lksh && bash ../Build.sh -L -M)",
  "jobs": {
    "include": [
      {
        "addons": {
          "apt": {
            "packages": [
              "ed"
            ]
          }
        },
        "arch": "amd64",
        "compiler": "gcc",
        "dist": "jammy",
        "os": "linux"
      },
      {
        "addons": {
          "apt": {
            "packages": [
              "ed"
            ]
          }
        },
        "arch": "arm64",
        "compiler": "gcc",
        "dist": "jammy",
        "os": "linux"
      },
      {
        "addons": {
          "apt": {
            "packages": [
              "ed"
            ]
          }
        },
        "arch": "ppc64le",
        "compiler": "gcc",
        "dist": "jammy",
        "os": "linux"
      },
      {
        "addons": {
          "apt": {
            "packages": [
              "ed"
            ]
          }
        },
        "arch": "s390x",
        "compiler": "gcc",
        "dist": "jammy",
        "os": "linux"
      },
      {
        "compiler": "clang",
        "os": "osx",
        "osx_image": "xcode7.3"
      },
      {
        "compiler": "clang",
        "os": "osx",
        "osx_image": "xcode12.2"
      },
      {
        "compiler": "clang",
        "os": "osx",
        "osx_image": "xcode13.4"
      },
      {
        "compiler": "clang",
        "os": "freebsd"
      }
    ]
  },
  "language": "c",
  "script": "set +e; unset -f cd; set -ex && for x in build-mksh build-lksh; do (cd $x && make -f GNUmakefile -j2 all && if script -qc true >/dev/null 2>&1; then script -qef -c 'make -f GNUmakefile regress'; else script -q typescript make -f GNUmakefile regress; fi && ./?ksh ../FAQ2HTML.sh); done"
}
