{
  "addons": {
    "coverity_scan": {
      "branch_pattern": "coverity_scan",
      "build_command": "sh -c 'set +e; unset -f cd; set -ex && for x in build-mksh build-lksh; do (cd $x && make -f GNUmakefile -j2 all); done'",
      "build_command_prepend": "set +e; unset -f cd; set -ex && rm -rf build* && mkdir build-mksh build-lksh && cp GNUmakefile build-mksh && cp GNUmakefile build-lksh && (cd build-mksh && sh ../Build.sh -M -g) && (cd build-lksh && bash ../Build.sh -L -M -g)",
      "notification_email": "tg@mirbsd.de",
      "project": {
        "description": "mksh Coverity/Travis",
        "name": "mirabilos/mksh"
      }
    }
  },
  "before_install": [
    "echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-",
    "sudo apt-get -qq update"
  ],
  "env": {
    "global": [
      {
        "secure": "Cb/kKOggE2OG5i0cWqYqF51kQIX7WUTnCcNUGG2t90G7qvOgQv4Mkzh6Ypn0zYxxsDq0jEqfVHUssOXzcXt3//Tc8UOnoXx91wczivHdEVgR1b6inREOphKnk2trW/sHR+DCQO8QfYyTd0Pjnr6WlYfpy8PVJuBg17yOnGjIWsgtdiH8uf1D9Ha0lu4cc1cR5f6XIfvR0+uPyVoRhhO+9hGEnGqnGeqxq6zxDKqDCClc6DkOsQxQFr7ykUDAQha44VIOJuie4uRAnBnAm25zRSJSRgYNAjXt6OybZgRXRo3GhrDWl5A6N/A2wVwtV5b2OWLFSLFUS3NcyOSawqA7qLS7iiddhK6h9dIyukdpyCo3UJlBz+5Mq/Pdu3YyDNz1LZDyuEp8tI8IgBxStQLvCCa//kfr597iaFkv3RTzuJ9uBBvE2o27Du49xr4zzSuqkVI45/MlxrFxbxBA7BeRYb08/YrO8PyiRG2ss3rzLpaJ4WPAvB5qXOdF78DgAYdAo/C9Uu7Z0qXyNxmPll5WTr1UY+3sKXpr50sy4fWlvwexoK9mu5VckKAybP/s7MQLapYp4Pv/0P+ayZXewkMixzyWdLxDNvg611TlLFnzl2IPRi1iRxe3Ul3MMNaG3JIXRdSg3dW/0qr/Dn6nAcZ47rHADb2gM8M20IE3eAPmh/s="
      }
    ]
  },
  "language": "c",
  "script": "true"
}
