{
  "jobs": {
    "bt-asan": {
      "runs-on": "ubuntu-22.04",
      "steps": [
        {
          "name": "Cancel previous runs",
          "uses": "styfle/cancel-workflow-action@0.10.0",
          "with": {
            "access_token": "${{ github.token }}",
            "all_but_latest": true
          }
        },
        {
          "uses": "actions/checkout@v3"
        },
        {
          "run": "echo foo ${{ matrix.testlksh }} baz"
        }
      ],
      "strategy": {
        "matrix": {
          "testlksh": [
            "",
            "-L"
          ]
        }
      }
    },
    "bt-normal": {
      "runs-on": "${{ matrix.os }}",
      "steps": [
        {
          "uses": "actions/checkout@v3"
        },
        {
          "run": "env CFLAGS='-O2 -Wformat-security -Wformat -Wall -Wextra' sh Build.sh ${{ matrix.testlksh }} -r && if script -qc true >/dev/null 2>&1; then script -qef -c './test.sh -f'; else script -q typescript ./test.sh -f; fi && ./?ksh FAQ2HTML.sh && echo Alles gut."
        }
      ],
      "strategy": {
        "matrix": {
          "os": [
            "ubuntu-22.04",
            "macos-11",
            "macos-12"
          ],
          "testlksh": [
            "",
            "-L"
          ]
        }
      }
    }
  },
  "name": "build-and-test",
  "on": {
    "push": {
      "branches": [
        "travis-ci"
      ]
    },
    "workflow_dispatch": null
  }
}
