{
  "jobs": {
    "doit": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v3.3.0",
          "with": {
            "token": "${{ secrets.WORKFLOW_SECRET }}"
          }
        },
        {
          "uses": "saadmk11/github-actions-version-updater@v0.7.3",
          "with": {
            "pull_request_user_reviewers": "mirabilos",
            "token": "${{ secrets.WORKFLOW_SECRET }}"
          }
        }
      ]
    }
  },
  "name": "GitHub Actions Version Updater",
  "on": "workflow_dispatch"
}
