{
  "jobs": {
    "doit": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v3.5.3",
          "with": {
            "token": "${{ secrets.WORKFLOW_SECRET }}"
          }
        },
        {
          "uses": "saadmk11/github-actions-version-updater@v0.8.1",
          "with": {
            "ignore": "github/codeql-action/init@v2,github/codeql-action/analyze@v2",
            "pull_request_user_reviewers": "mirabilos",
            "token": "${{ secrets.WORKFLOW_SECRET }}"
          }
        }
      ]
    }
  },
  "name": "GitHub Actions Version Updater",
  "on": "workflow_dispatch"
}
