{
  "jobs": {
    "vm-dflybsd": {
      "runs-on": "macos-12",
      "steps": [
        {
          "uses": "actions/checkout@v3.3.0"
        },
        {
          "run": "(git gc || :)"
        },
        {
          "uses": "vmactions/dragonflybsd-vm@v0.0.6",
          "with": {
            "copyback": false,
            "mem": 2048,
            "prepare": "pkg install -y perl5",
            "run": "tryshell=sh; nextshell=sh; set -ex; rm -rf build; mkdir build; flag=; for dir in mksh lksh; do mkdir build/$dir; cd build/$dir; $tryshell ../../Build.sh $flag -r; if script -qc true >/dev/null 2>&1; then script -qef -c './test.sh -f'; else script -q typescript ./test.sh -f; fi; ./?ksh ../../FAQ2HTML.sh; cd ../..; tryshell=$nextshell; flag=-L; done; echo Alles gut.",
            "usesh": true
          }
        }
      ]
    }
  },
  "name": "vm-dfbsd",
  "on": {
    "workflow_dispatch": null
  }
}
