{
  "jobs": {
    "vm-fbsd": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v4.1.1"
        },
        {
          "run": "(git gc --quiet || :)"
        },
        {
          "uses": "vmactions/freebsd-vm@v1.0.5",
          "with": {
            "copyback": false,
            "mem": 2048,
            "prepare": "pkg install -y perl5",
            "run": "tryshell=sh; nextshell=sh; set -ex; rm -rf build; mkdir build; flag=; for dir in mksh lksh; do mkdir build/$dir; cd build/$dir; test -z \"$flag\" || cp ../../.extra/printf.c .; $tryshell ../../Build.sh $flag -r; if script -qc true >/dev/null 2>&1; then script -qef -c './test.sh'; else script -q typescript ./test.sh; fi; ./?ksh ../../FAQ2HTML.sh; cd ../..; tryshell=$nextshell; flag=-L; USE_PRINTF_BUILTIN=1; export USE_PRINTF_BUILTIN; CPPFLAGS=\"$CPPFLAGS -DMKSH_BINSHPOSIX -DMKSH_BINSHREDUCED\"; export CPPFLAGS; done; echo Alles gut.",
            "usesh": true
          }
        }
      ]
    }
  },
  "name": "vm-fbsd",
  "on": {
    "workflow_dispatch": null
  }
}
