{
  "jobs": {
    "vm-obsd": {
      "runs-on": "macos-12",
      "steps": [
        {
          "uses": "actions/checkout@v3.3.0"
        },
        {
          "run": "(git gc || :)"
        },
        {
          "uses": "vmactions/openbsd-vm@v0.1.1",
          "with": {
            "copyback": false,
            "mem": 2048,
            "run": "tryshell=ksh; nextshell=sh; set -ex; rm -rf build; mkdir build; flag=; for dir in mksh lksh; do mkdir build/$dir; cd build/$dir; $tryshell ../../Build.sh $flag -r; echo 255 >test.res; echo >test.wait; (script -c './test.sh -f; echo $? >test.res; sleep 1; rm -f test.wait'; maxwait=0; while test -e test.wait; do sleep 1; maxwait=$(expr $maxwait + 1); test $maxwait -lt 900 || break; done; exit \"$(cat test.res)\"); ./?ksh ../../FAQ2HTML.sh; cd ../..; tryshell=$nextshell; flag=-L; done; echo Alles gut.",
            "usesh": true
          }
        }
      ]
    }
  },
  "name": "vm-obsd",
  "on": {
    "workflow_dispatch": null
  }
}
