{
  "jobs": {
    "vm-slowlartus": {
      "runs-on": "macos-12",
      "steps": [
        {
          "uses": "actions/checkout@v3.3.0"
        },
        {
          "run": "(git gc || :)"
        },
        {
          "uses": "vmactions/solaris-vm@v0.0.9",
          "with": {
            "copyback": false,
            "mem": 2048,
            "prepare": "pkgutil -y -i gcc5core",
            "run": "CC=gcc; export CC; tryshell=/bin/sh; nextshell=bash; set -ex; rm -rf build; mkdir build; flag=; for dir in mksh lksh; do mkdir build/$dir; cd build/$dir; $tryshell ../../Build.sh $flag -r; echo 255 >test.res; echo >test.wait; :>screenlog.0; tail -f screenlog.0 & bpid=$!; screen -d -m -L sh -c './test.sh -f; echo $? >test.res; sleep 1; rm -f test.wait'; maxwait=0; while test -e test.wait; do sleep 1; maxwait=$(expr $maxwait + 1); test $maxwait -lt 900 || break; done; theres=$(cat test.res); echo === \"$theres\"; kill $bpid || :; test x\"$theres\" = x\"0\"; ./?ksh ../../FAQ2HTML.sh; cd ../..; tryshell=$nextshell; flag=-L; done; echo Alles gut.",
            "usesh": true
          }
        }
      ]
    }
  },
  "name": "vm-slowlartus",
  "on": {
    "workflow_dispatch": null
  }
}
